
ALTER TABLE public.site_settings
  ADD COLUMN IF NOT EXISTS favicon_url text,
  ADD COLUMN IF NOT EXISTS og_image_url text,
  ADD COLUMN IF NOT EXISTS meta_description_ar text,
  ADD COLUMN IF NOT EXISTS meta_description_en text,
  ADD COLUMN IF NOT EXISTS meta_description_ur text,
  ADD COLUMN IF NOT EXISTS meta_keywords text,
  ADD COLUMN IF NOT EXISTS default_language text NOT NULL DEFAULT 'ar',
  ADD COLUMN IF NOT EXISTS maintenance_mode boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS maintenance_message text,
  ADD COLUMN IF NOT EXISTS allow_signups boolean NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS allow_guest_checkout boolean NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS require_email_verification boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS vat_percent numeric NOT NULL DEFAULT 10,
  ADD COLUMN IF NOT EXISTS prices_include_vat boolean NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS low_stock_threshold integer NOT NULL DEFAULT 5,
  ADD COLUMN IF NOT EXISTS company_address text,
  ADD COLUMN IF NOT EXISTS company_cr text,
  ADD COLUMN IF NOT EXISTS company_vat_no text,
  ADD COLUMN IF NOT EXISTS business_hours text,
  ADD COLUMN IF NOT EXISTS primary_color text DEFAULT '#22d3ee',
  ADD COLUMN IF NOT EXISTS accent_color text DEFAULT '#0ea5e9',
  ADD COLUMN IF NOT EXISTS google_analytics_id text,
  ADD COLUMN IF NOT EXISTS meta_pixel_id text,
  ADD COLUMN IF NOT EXISTS tiktok_pixel_id text,
  ADD COLUMN IF NOT EXISTS custom_head_html text,
  ADD COLUMN IF NOT EXISTS announcement_bar_text text,
  ADD COLUMN IF NOT EXISTS announcement_bar_enabled boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS notify_email_new_order boolean NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS notify_email_low_stock boolean NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS instagram_url text,
  ADD COLUMN IF NOT EXISTS twitter_url text,
  ADD COLUMN IF NOT EXISTS facebook_url text,
  ADD COLUMN IF NOT EXISTS tiktok_url text,
  ADD COLUMN IF NOT EXISTS youtube_url text,
  ADD COLUMN IF NOT EXISTS snapchat_url text,
  ADD COLUMN IF NOT EXISTS telegram_url text;
